name:                hsforce
version:             0.1.2.0
github:              "tzmfreedom/hsforce"
license:             BSD3
author:              "Makoto Tajitsu"
maintainer:          "makoto_tajitsu@hotmail.co.jp"
copyright:           "2019 Makoto Tajitsu"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Salesforce API Client
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         This package provides bindings to Salesforce API <https://github.com/tzmfreedom/hsforce#readme>

default-extensions:
- DuplicateRecordFields
- ScopedTypeVariables

dependencies:
- base                 >= 4.7 && < 5
- HaXml                >= 1.25.4 && < 1.26
- bytestring           >= 0.10.8 && < 0.11
- text                 >= 1.2.2 && < 1.3
- aeson                >= 1.4.2 && < 1.5
- aeson-pretty
- lens                 >= 4.17
- lens-aeson           >= 1.0.2
- template-haskell     >= 2.14.0 && < 2.15
- unordered-containers >= 0.2.7 && < 0.3
- fast-tagsoup         >= 1.0.14 && < 1.1
- tagsoup              >= 0.14.7 && < 0.15
- http-conduit         >= 2.3.4 && < 2.4
- network-uri          >= 2.6.1 && < 2.7
- regex-posix          >= 0.95.2 && < 0.96
- uri-encode           >= 1.5.0 && < 1.6

library:
  source-dirs: src
#
#executables:
#  hsforce-exe:
#    main:                Main.hs
#    source-dirs:         app
#    ghc-options:
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
#    dependencies:
#    - hsforce

tests:
  hsforce-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hsforce
